<?php

/**
 * @file
 * Run update hooks and system wide functionality for my-bd-bd app.
 */

/**
 *
 */
function my_core_menu() {
  $items = array();
  $items['geoff'] = array(
    'title' => 'geoff is the best',
    'access callback' => TRUE,
    'page callback' => 'my_core_geoff_is_the_best',
  );

  return $items;
}

/**
 * Page callback for menu item 'geoff'.
 */
function my_core_geoff_is_the_best($gff) {
  $markup = 'geoff is the best.';

  return $markup;
}
